cat > .github/workflows/test-upload.yml <<'EOF'name: Lighthouse CI

on:
  # push:
  #   branches: [ main, master ]
  workflow_dispatch:

# Give the workflow permission to upload artifacts and perform Actions operations.
permissions:
  actions: write
  contents: read

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Wait for HTTPS and valid TLS
        run: |
          set -e
          url="opach.online"
          timeout=900
          interval=10
          elapsed=0

          echo "Waiting up to $timeout s for HTTPS and valid certificate at https://$url..."

          while [ $elapsed -lt $timeout ]; do
            http_code=$(curl -s -o /dev/null -w "%{http_code}" -I https://$url || true)
            cert_ok=$(echo | openssl s_client -servername $url -connect $url:443 2>/dev/null \
                      | openssl x509 -noout -checkend 60 >/dev/null 2>&1 && echo "1" || echo "0")

            if [ "$http_code" = "200" ] || [ "$http_code" = "301" ] || [ "$http_code" = "302" ]; then
              if [ "$cert_ok" = "1" ]; then
                echo "HTTPS + cert OK (http_code=$http_code)"
                exit 0
              fi
            fi

            echo "Not ready yet (http_code=$http_code, cert_ok=$cert_ok). Sleeping $interval s..."
            sleep $interval
            elapsed=$((elapsed + interval))
          done

          echo "Timed out waiting for HTTPS/certificate after $timeout seconds"
          exit 1

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Lighthouse on live site (no internal uploads)
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://opach.online
          uploadArtifacts: false
          temporaryPublicStorage: false
          configPath: ""
          runs: 1

      - name: Locate Lighthouse files (build TAR) 
        id: pack_reports
        run: |
          set -e
          OUT_TAR="/tmp/lighthouse_reports_${GITHUB_RUN_ID}.tar.gz"
          # common locations/names generated by lighthouse-ci / lighthouse:
          candidates=(
            "./lighthouse-report"
            "./.lighthouseci"
            "./lhr"
            "./reports"
            "./lhci"
            "./lighthouse"
          )

          echo "Searching for candidate report dirs and files..."
          found=false
          # collect files into a temp dir
          TMPDIR="/tmp/lh_collect_${GITHUB_RUN_ID}"
          mkdir -p "$TMPDIR"

          for d in "${candidates[@]}"; do
            if [ -d "$d" ]; then
              echo "Found dir: $d"
              cp -a "$d/." "$TMPDIR/" || true
              found=true
            fi
          done

          # find common file patterns
          shopt -s nullglob
          for f in $(find . -maxdepth 3 -type f \( -iname "*lighthouse*.html" -o -iname "*.report.html" -o -iname "*.lhr.json" -o -iname "*.report.json" -o -iname "*.html" -o -iname "*.json" \) ); do
            # skip node_modules and .git and /tmp directories
            case "$f" in
              ./node_modules/*|./.git/*|/tmp/*) continue ;;
            esac
            echo "Found file: $f"
            mkdir -p "$(dirname "$TMPDIR/$f")"
            cp -a "$f" "$TMPDIR/$f" || true
            found=true
          done

          if [ "$found" = false ]; then
            echo "No lighthouse report files found. Nothing to upload."
            echo "report_exists=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # create tarball
          tar -C "$TMPDIR" -czf "$OUT_TAR" .
          echo "report_exists=true" >> "$GITHUB_OUTPUT"
          echo "tar_path=$OUT_TAR" >> "$GITHUB_OUTPUT"
          ls -la "$OUT_TAR"
      
      - name: Debug: show tar contents (if present)
        if: ${{ steps.pack_reports.outputs.report_exists == 'true' }}
        run: |
          tar -tzf ${{ steps.pack_reports.outputs.tar_path }} | head -n 50 || true

      - name: Upload Lighthouse results artifact
        if: ${{ steps.pack_reports.outputs.report_exists == 'true' && ((github.event_name != 'pull_request') || (github.event.pull_request.head.repo.full_name == github.repository)) }}
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports-${{ github.run_id }}
          path: ${{ steps.pack_reports.outputs.tar_path }}

      - name: Show artifact name (for logs)
        if: ${{ steps.pack_reports.outputs.report_exists == 'true' && ((github.event_name != 'pull_request') || (github.event.pull_request.head.repo.full_name == github.repository)) }}
        run: |
          echo "Uploaded artifact: lighthouse-reports-${GITHUB_RUN_ID}" EOF
